# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:05:16+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Query

from models import Alt, ClientInfoPlatform, FieldXgafv, TerrainFormats, TerrainTile

app = MCPProxy(
    contact={'name': 'Google', 'url': 'https://google.com', 'x-twitter': 'youtube'},
    description='Serves vector tiles containing geospatial data. ',
    license={
        'name': 'Creative Commons Attribution 3.0',
        'url': 'http://creativecommons.org/licenses/by/3.0/',
    },
    termsOfService='https://developers.google.com/terms/',
    title='Semantic Tile API',
    version='v1',
    servers=[{'url': 'https://vectortile.googleapis.com/'}],
)


@app.get(
    '/v1/{name}',
    description=""" Gets a terrain tile by its tile resource name. """,
    tags=['terrain_tile_management'],
)
def vectortile_terraintiles_get(
    name: str,
    altitude_precision_centimeters: Optional[int] = Query(
        None, alias='altitudePrecisionCentimeters'
    ),
    client_info_api_client: Optional[str] = Query(None, alias='clientInfo.apiClient'),
    client_info_application_id: Optional[str] = Query(
        None, alias='clientInfo.applicationId'
    ),
    client_info_application_version: Optional[str] = Query(
        None, alias='clientInfo.applicationVersion'
    ),
    client_info_device_model: Optional[str] = Query(
        None, alias='clientInfo.deviceModel'
    ),
    client_info_operating_system: Optional[str] = Query(
        None, alias='clientInfo.operatingSystem'
    ),
    client_info_platform: Optional[ClientInfoPlatform] = Query(
        None, alias='clientInfo.platform'
    ),
    client_info_user_id: Optional[str] = Query(None, alias='clientInfo.userId'),
    max_elevation_resolution_cells: Optional[int] = Query(
        None, alias='maxElevationResolutionCells'
    ),
    min_elevation_resolution_cells: Optional[int] = Query(
        None, alias='minElevationResolutionCells'
    ),
    terrain_formats: Optional[TerrainFormats] = Query(None, alias='terrainFormats'),
    enable_modeled_volumes: Optional[bool] = Query(None, alias='enableModeledVolumes'),
    enable_political_features: Optional[bool] = Query(
        None, alias='enablePoliticalFeatures'
    ),
    enable_private_roads: Optional[bool] = Query(None, alias='enablePrivateRoads'),
    enable_unclipped_buildings: Optional[bool] = Query(
        None, alias='enableUnclippedBuildings'
    ),
    language_code: Optional[str] = Query(None, alias='languageCode'),
    region_code: Optional[str] = Query(None, alias='regionCode'),
    field__xgafv: Optional[FieldXgafv] = Query(None, alias='$.xgafv'),
    access_token: Optional[str] = None,
    alt: Optional[Alt] = None,
    callback: Optional[str] = None,
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(None, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    upload_protocol: Optional[str] = None,
    upload_type: Optional[str] = Query(None, alias='uploadType'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
